### ISSUE TITLE
Possibly incompatible with nodeJS 4.0.0 ?

### ISSUE THREAD

**Issue by bogas04** [peterbraden/node-opencv#293] opened 2015-09-10 10:43 UTC
I get following error while installing opencv using npm on OSX machine with OpenCV 2.4.12 installed using homebrew
```bash
npm install opencv
\
> opencv@3.2.0 install /Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv
> node-pre-gyp install --fallback-to-build

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:12:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/USER/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/USER/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const
      qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/USER/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/USER/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:12:
../node_modules/nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:12:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:4:
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:4:
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:4:
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/init.cc:1:
In file included from ../src/OpenCV.h:4:
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/USER/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
10 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.2.0" "--major=3" "--minor=2" "--runtime=node" "--node_abi=node-v46" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-darwin-x64" "--module=/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-darwin-x64/opencv.node" "--remote_path=./opencv/v3.2.0/Release/" "--package_name=node-v46-darwin-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.2.0/Release/node-v46-darwin-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-darwin-x64.tar.gz"
gyp ERR! cwd /Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/iojs /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v46 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-darwin-x64 --module=/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-darwin-x64/opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v46-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.2.0/Release/node-v46-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/bin/iojs" "/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/iojs /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.2.0 --major=3 --minor=2 --runtime=node --node_abi=node-v46 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-darwin-x64 --module=/Users/USER/Work/Code/NodeJS/FaceRecog/node_modules/opencv/build/opencv/v3.2.0/Release/node-v46-darwin-x64/opencv.node --remote_path=./opencv/v3.2.0/Release/ --package_name=node-v46-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.2.0/Release/node-v46-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.2.0/Release/node-v46-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/USER/Work/Code/NodeJS/FaceRecog/npm-debug.log
```

**Comment by bogas04** [comment] 2015-09-10 11:07
It builds well on using 0.12.7

**Comment by eliothxchan** [comment] 2015-09-11 13:42
+1, isn't properly installing for me, either

**Comment by ChALkeR** [comment] 2015-09-12 17:14
Adding to the list: https://github.com/nodejs/node/issues/2798.
`nan` dependency has to be updated to v2.

**Comment by JonnyBGod** [comment] 2015-09-16 01:46
+1

**Comment by davduran** [comment] 2015-09-25 10:01
+1

**Comment by keeganbrown** [comment] 2015-09-29 16:59
+1

**Comment by emaggini** [comment] 2015-09-30 00:51
+1 I am encountering this issue on Raspberry Pi B running Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux

Node version v0.12.6

**Comment by aaaristo** [comment] 2015-10-01 12:34
+1

**Comment by BryceBeagle** [comment] 2015-10-02 01:02
+1

**Comment by keeganbrown** [comment] 2015-10-02 16:03
I've got a fork with it building correct using node 4.1.1, but failing to build in 0.12.7, if anyone has time to figure out how to make it work in both. Here's my pull request: https://github.com/peterbraden/node-opencv/pull/309

**Comment by lzfelix** [comment] 2015-10-05 13:35
+1.
Using node 4.1.1 and openCV 2.4.12 installed by using brew.

**Comment by albertgarcias** [comment] 2015-10-05 15:07
+1

**Comment by davduran** [comment] 2015-10-05 15:11
As other people say, the best solution (tested in Mac and Ubuntu) is install node 4.x and openCV 2.4.x

**Comment by lzfelix** [comment] 2015-10-05 15:12
@davduran. I'm trying to do this but didn't succeed yet.

**Comment by albertgarcias** [comment] 2015-10-05 15:14
I'm using windows 7 with Node 4.1.1 with OpenCV 2.4.11 and I'm having the same issue.

**Comment by davduran** [comment] 2015-10-05 15:25
1) First uninstall your current openCV. 

2) Then install "brew".

3) In the terminal: brew install opencv

4) Check the openCV version installed: 
In linux/mac with command: make sure pkg-config --cflags 
You shoul'd get something like this: -I/usr/local/davduran/opencv/2.4.11_1/include/opencv -I/usr/local/davduran/opencv/2.4.11_1/include

5) Now go to you node/project folder. And type in the terminal: npm install opencv --save

*Maybe you get some warnings but the project finally compile.

**Comment by davduran** [comment] 2015-10-05 15:26
If I have some time I will publish a script that automates the process.

**Comment by lzfelix** [comment] 2015-10-05 15:27
That's what I'm getting: http://pastebin.com/pVbsA3eL

**Comment by davduran** [comment] 2015-10-05 15:32
@lzfelix Look line #3:

> opencv@3.2.0 install /Users/luiz/Downloads/config-0.3.9/node_modules/opencv

You're trying to compile/install with opencv 3.2.0. You must ensure uninstall opencv 3.x from your system and the install 2.4.x.

**Comment by davduran** [comment] 2015-10-05 15:40
Sorry try with: pkg-config --cflags opencv

**Comment by lzfelix** [comment] 2015-10-05 15:41
@davduran, the problem is that I've never install opencv before and when I do so using brew, it downloads version 2.4.x.
Is there any way for me to find this opencv3.x version that is seems to be installed on osx?

**Comment by davduran** [comment] 2015-10-05 15:53
Try "pkg-config --cflags opencv" and showme what returns.

**Comment by lzfelix** [comment] 2015-10-05 15:55
Still the same. To ensure my openCV version, I listed the Cellar from brew:
$ ls /usr/local/Cellar/opencv/
2.4.12/
Which shows that I'm using the correct version of native openCV and that 3.2.0 is node's OpenCV version.

**Comment by davduran** [comment] 2015-10-05 16:05
Ok, let's try from another point of view:
STRIKE 1:
1) Go to node_modules in your project folder.
2) Add opencv to the dependencies section in package.json.
3) Try with: npm install

STRIKE 2:
1) Go to node_modules in your project folder.
2) Download the node-opencv master to here and rename the folder to "opencv".
3) Go to the root folder of the project and type: npm install

**Comment by davduran** [comment] 2015-10-05 19:30
OK. I just make the whole process from 0...

/*Mac Instructions*/
1) Uninstall OpenCV 3.0
2) Install "brew"
3) In the terminal: brew install opencv
4) Go to node_modules in your project folder.
5) Download node_opencv_master
6) Unzip and rename the folder to "opencv"
7) Enter to "opencv" and make: npm install  (some warnings on this step but don't worry)
8) Now you can exit to the root project. And throw a normal "npm install" (just npm install, without opencv).

Voilà! Now compiles and the examples works.

**Comment by davduran** [comment] 2015-10-05 19:45
PLUS: To solve error of pkg_config path----> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

**Comment by lzfelix** [comment] 2015-10-05 23:32
@davduran, my previous strategy also work, but can you please confirm your node version (``node --version`` ?). I'm just letting this here for anyone having the same problem:

- upload your Xcode to version 7
- ensure to have cmake instlled (``brew install cmake``)
- then install opencv (not node's opencv). By default brew install version 2.x. Do this by ``brew install opencv``
- according to [this post](https://github.com/nodejs/node/issues/2798) node's opencv is incompatibe witn Node 4.x due to dependencies NAN. I switched no node 0.12.7 using [nvm](https://github.com/creationix/nvm)
- finally run ``npm install opencv``

**Comment by joaolucasl** [comment] 2015-10-06 06:59
+1 for the error.
@lzfelix approach worked *fine*

**Comment by lzfelix** [comment] 2015-10-06 13:57
According to @joaolucasl, it works on Linux too (of course, you have to manage to download opencv and cmake without brew).

**Comment by peterbraden** [comment] 2015-10-07 14:13
I just merged #309 which should fix that, can you try `npm install peterbraden/node-opencv` and see if this works for you all?

**Comment by adius** [comment] 2015-10-08 13:28
Thanks @davduran for the step by step help. Worked for me.
@peterbraden How about releasing the current master as a new version, so that the latest release contains all the bugfixes?

**Comment by peterbraden** [comment] 2015-10-08 13:36
Yep, I definitely plan on doing this soon, I was hoping that people could confirm that the master branch fixes their issues before cutting the release.

**Comment by lzfelix** [comment] 2015-10-09 00:58
@peterbraden, it's working fine for me too.

**Comment by VansonLeung** [comment] 2015-10-10 04:52
@davduran 

Annotated /Mac Instructions/
1) Uninstall OpenCV 3.0    <<<  This is the key step! Download OpenCV 3.0 Build, and run "sudo make uninstall"
2) Install "brew"
3) In the terminal: brew install opencv
4) Go to node_modules in your project folder.
5) Download node_opencv_master
6) Unzip and rename the folder to "opencv"
7) Enter to "opencv" and make: npm install (some warnings on this step but don't worry)
8) Now you can exit to the root project. And throw a normal "npm install" (just npm install, without opencv).

**Comment by keeganbrown** [comment] 2015-10-16 19:05
So has anyone other than me tried installing this with Node 4+, using @peterbraden instructions above? I've got it working correctly in Ubuntu 14.04 and Raspian Wheezy (with some help from Jessie).

**Comment by youweit** [comment] 2015-10-22 06:11
@davduran thanks! it works!

**Comment by jskrzypek** [comment] 2015-10-22 09:34
I had a really tough time with this on Yosemite with node v4.2.1 and opencv v2.4.1 (and XCode 7.0.1)... npm simply refused to install the package.

until just now when I realized gyp was failing beacuse I didn't have pkg-config installed from brew.  Running `brew install pkg-config` fixed it and I was able to get it installed. Thanks all!

**Comment by jskrzypek** [comment] 2015-10-22 09:41
I spoke a bit too soon... there was a conflict with the way npm@3.3.8 was resolving a sub-sub-dep but clone this repo and using `npm link` worked :)

**Comment by joerex** [comment] 2015-11-10 16:00
If it helps anyone, I was having trouble with this error after going to the latest node (opencv 2.4.12 / node 4.2.1):

> opencv@3.2.0 install /Users/joe/Projects/isolator-module/node_modules/opencv
> node-pre-gyp install --fallback-to-build

> (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
> gyp: /Users/joe/.node-gyp/4.2.1/common.gypi not found (cwd: /Users/joe/Projects/isolator-
> module/node_modules/opencv) while reading includes of binding.gyp while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1

Installing the latest version of npm and rebuilding solved this:
sudo npm install -g npm@latest
npm install
npm rebuild

**Comment by xenomuta** [comment] 2015-11-11 21:50
@peterbraden this fix works for me: node v0.12.x and v4.2.1.  :+1:

**Comment by dustinaevans** [comment] 2016-04-04 12:09
Had this issue. Fixed with brew install pkgconfig.

**Comment by danschultzer** [comment] 2016-09-22 19:39
It seems that after #309, rebuilding and installing `pkg-config` resolves this. I'll close the issue. Reply if you still experience it, and I'll reopen.

**Closed by danschultzer** 2016-09-22 19:39 UTC
